export interface CatalogPlant {
  id: number;
  type: "indoor" | "outdoor";
  typeLabel: "داخلي" | "خارجي";
  name: string;
  scientificOrAlt?: string;
  priority: 1 | 2 | 3;
  priorityBadge: "🔥" | "🔥🔥" | "🔥🔥🔥";
  priorityLabel: "أولوية خاصة" | "أولوية عالية" | "أولوية قصوى";
}

export const indoorPlants: CatalogPlant[] = [
  { id: 1, type: "indoor", typeLabel: "داخلي", name: "بوتس ذهبي Pothos", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 2, type: "indoor", typeLabel: "داخلي", name: "سانسيفيريا / جلد النمر", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 3, type: "indoor", typeLabel: "داخلي", name: "الزاميا ZZ", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 4, type: "indoor", typeLabel: "داخلي", name: "فيلوديندرون القلب", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 5, type: "indoor", typeLabel: "داخلي", name: "سبايدر بلانت / نبات العنكبوت", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 6, type: "indoor", typeLabel: "داخلي", name: "مونستيرا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 7, type: "indoor", typeLabel: "داخلي", name: "دراسينا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 8, type: "indoor", typeLabel: "داخلي", name: "فيكس بنجامينا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 9, type: "indoor", typeLabel: "داخلي", name: "شفليرا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 10, type: "indoor", typeLabel: "داخلي", name: "أنثوريوم", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 11, type: "indoor", typeLabel: "داخلي", name: "أجلاونيما", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 12, type: "indoor", typeLabel: "داخلي", name: "بامبو الحظ", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 13, type: "indoor", typeLabel: "داخلي", name: "فيلوديندرون برازيـل", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 14, type: "indoor", typeLabel: "داخلي", name: "بوتس نيون", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 15, type: "indoor", typeLabel: "داخلي", name: "بوتس إنجوي", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 16, type: "indoor", typeLabel: "داخلي", name: "بوتس ماربل كوين", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 17, type: "indoor", typeLabel: "داخلي", name: "فيكس مطاط / Rubber Plant", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 18, type: "indoor", typeLabel: "داخلي", name: "دراسينا ماسنجانا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 19, type: "indoor", typeLabel: "داخلي", name: "دراسينا ليمون لايم", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 20, type: "indoor", typeLabel: "داخلي", name: "دراسينا كومباكتا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 21, type: "indoor", typeLabel: "داخلي", name: "كالاتيا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 22, type: "indoor", typeLabel: "داخلي", name: "مارانتا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 23, type: "indoor", typeLabel: "داخلي", name: "كروتون", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 24, type: "indoor", typeLabel: "داخلي", name: "ببروميا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 25, type: "indoor", typeLabel: "داخلي", name: "ديفنباخيا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 26, type: "indoor", typeLabel: "داخلي", name: "ألوكاسيا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 27, type: "indoor", typeLabel: "داخلي", name: "كورديلين", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 28, type: "indoor", typeLabel: "داخلي", name: "فيتونيا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 29, type: "indoor", typeLabel: "داخلي", name: "أوركيد فالاينوبسيس", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 30, type: "indoor", typeLabel: "داخلي", name: "بنفسج إفريقي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 31, type: "indoor", typeLabel: "داخلي", name: "بيليا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 32, type: "indoor", typeLabel: "داخلي", name: "كالانشو", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 33, type: "indoor", typeLabel: "داخلي", name: "هويا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 34, type: "indoor", typeLabel: "داخلي", name: "صبار الألوفيرا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 35, type: "indoor", typeLabel: "داخلي", name: "صبار داخلي صغير", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 36, type: "indoor", typeLabel: "داخلي", name: "هاروثيا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 37, type: "indoor", typeLabel: "داخلي", name: "إيشيفيريا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 38, type: "indoor", typeLabel: "داخلي", name: "سيدوم", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 39, type: "indoor", typeLabel: "داخلي", name: "نبات الصلاة", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 40, type: "indoor", typeLabel: "داخلي", name: "نخلة الأريكا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 41, type: "indoor", typeLabel: "داخلي", name: "نخلة شاميدوريا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 42, type: "indoor", typeLabel: "داخلي", name: "يوكا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 43, type: "indoor", typeLabel: "داخلي", name: "بيوكارنيا / ذيل الحصان", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 44, type: "indoor", typeLabel: "داخلي", name: "نخلة كينتيا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 45, type: "indoor", typeLabel: "داخلي", name: "فيكس ليراتا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 46, type: "indoor", typeLabel: "داخلي", name: "فيكس ميكروكاربا / بونساي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 47, type: "indoor", typeLabel: "داخلي", name: "سينجونيوم", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 48, type: "indoor", typeLabel: "داخلي", name: "سكندابسوس / بوتس فضي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 49, type: "indoor", typeLabel: "داخلي", name: "ريكس بيجونيا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 50, type: "indoor", typeLabel: "داخلي", name: "نبات القفص الصدري / Monstera Adansonii", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
];

export const outdoorPlants: CatalogPlant[] = [
  { id: 1, type: "outdoor", typeLabel: "خارجي", name: "جهنمية", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 2, type: "outdoor", typeLabel: "خارجي", name: "ياسمين هندي / بلوميريا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 3, type: "outdoor", typeLabel: "خارجي", name: "واشنطونيا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 4, type: "outdoor", typeLabel: "خارجي", name: "سدر", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 5, type: "outdoor", typeLabel: "خارجي", name: "زيتون", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 6, type: "outdoor", typeLabel: "خارجي", name: "ليمون", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 7, type: "outdoor", typeLabel: "خارجي", name: "فيكس بنجامينا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 8, type: "outdoor", typeLabel: "خارجي", name: "نيم", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 9, type: "outdoor", typeLabel: "خارجي", name: "غاف / مسكيت", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 10, type: "outdoor", typeLabel: "خارجي", name: "أكاسيا", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
  { id: 11, type: "outdoor", typeLabel: "خارجي", name: "تيكوما صفراء", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 12, type: "outdoor", typeLabel: "خارجي", name: "لانتانا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 13, type: "outdoor", typeLabel: "خارجي", name: "كف مريم / فيتكس", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 14, type: "outdoor", typeLabel: "خارجي", name: "دفلة", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 15, type: "outdoor", typeLabel: "خارجي", name: "ياسمين بلدي", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 16, type: "outdoor", typeLabel: "خارجي", name: "ياسمين زفر", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 17, type: "outdoor", typeLabel: "خارجي", name: "فل بلدي", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 18, type: "outdoor", typeLabel: "خارجي", name: "فل جيزاني", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 19, type: "outdoor", typeLabel: "خارجي", name: "هبسكس", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 20, type: "outdoor", typeLabel: "خارجي", name: "كنا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 21, type: "outdoor", typeLabel: "خارجي", name: "بفتة", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 22, type: "outdoor", typeLabel: "خارجي", name: "كروتون خارجي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 23, type: "outdoor", typeLabel: "خارجي", name: "روهو", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 24, type: "outdoor", typeLabel: "خارجي", name: "أكاليفا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 25, type: "outdoor", typeLabel: "خارجي", name: "جتروفا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 26, type: "outdoor", typeLabel: "خارجي", name: "كريسيا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 27, type: "outdoor", typeLabel: "خارجي", name: "تيكوماريا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 28, type: "outdoor", typeLabel: "خارجي", name: "دادونيا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 29, type: "outdoor", typeLabel: "خارجي", name: "بزروميا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 30, type: "outdoor", typeLabel: "خارجي", name: "جاكرندا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 31, type: "outdoor", typeLabel: "خارجي", name: "بونسيانا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 32, type: "outdoor", typeLabel: "خارجي", name: "لبخ", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 33, type: "outdoor", typeLabel: "خارجي", name: "كورديا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 34, type: "outdoor", typeLabel: "خارجي", name: "أكاسيا جلوكا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 35, type: "outdoor", typeLabel: "خارجي", name: "باركنسونيا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 36, type: "outdoor", typeLabel: "خارجي", name: "فرشاة الزجاج", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 37, type: "outdoor", typeLabel: "خارجي", name: "تمر هندي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 38, type: "outdoor", typeLabel: "خارجي", name: "رمان", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 39, type: "outdoor", typeLabel: "خارجي", name: "توت", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 40, type: "outdoor", typeLabel: "خارجي", name: "برتقال", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 41, type: "outdoor", typeLabel: "خارجي", name: "يوسفي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 42, type: "outdoor", typeLabel: "خارجي", name: "تين", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 43, type: "outdoor", typeLabel: "خارجي", name: "مورينجا", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 44, type: "outdoor", typeLabel: "خارجي", name: "أراك", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 45, type: "outdoor", typeLabel: "خارجي", name: "أثل", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 46, type: "outdoor", typeLabel: "خارجي", name: "طلح / سمر", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 47, type: "outdoor", typeLabel: "خارجي", name: "صبار أمريكي", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 48, type: "outdoor", typeLabel: "خارجي", name: "ألوفيرا", priority: 2, priorityBadge: "🔥🔥", priorityLabel: "أولوية عالية" },
  { id: 49, type: "outdoor", typeLabel: "خارجي", name: "صبار عمودي", priority: 1, priorityBadge: "🔥", priorityLabel: "أولوية خاصة" },
  { id: 50, type: "outdoor", typeLabel: "خارجي", name: "نخيل عربي / نخيل تمر", priority: 3, priorityBadge: "🔥🔥🔥", priorityLabel: "أولوية قصوى" },
];

export const allPlantsCatalog: CatalogPlant[] = [
  ...indoorPlants,
  ...outdoorPlants.map((p) => ({ ...p, id: p.id + 50 })),
];
