export interface CatalogPlant {
  id: number;
  type: "indoor" | "outdoor";
  typeLabel: "داخلي" | "خارجي";
  name: string;
  scientificOrAlt?: string;
  priority: 1 | 2 | 3;
  priorityBadge: "🔥" | "🔥🔥" | "🔥🔥🔥";
  priorityLabel: "أولوية خاصة" | "أولوية عالية" | "أولوية قصوى";
  image: string;
}

export const indoorPlants: CatalogPlant[] = [
  {
    id: 1,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس ذهبي Pothos",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-pothos.jpg",
  },
  {
    id: 2,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سانسيفيريا / جلد النمر",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-sansevieria.jpg",
  },
  {
    id: 3,
    type: "indoor",
    typeLabel: "داخلي",
    name: "الزاميا ZZ",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1632207691143-643e2a9a9361?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 4,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيلوديندرون القلب",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 5,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سبايدر بلانت / نبات العنكبوت",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1596724817753-e5229712bf37?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 6,
    type: "indoor",
    typeLabel: "داخلي",
    name: "مونستيرا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-monstera.jpg",
  },
  {
    id: 7,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-dracaena.jpg",
  },
  {
    id: 8,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس بنجامينا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 9,
    type: "indoor",
    typeLabel: "داخلي",
    name: "شفليرا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 10,
    type: "indoor",
    typeLabel: "داخلي",
    name: "أنثوريوم",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1604762524889-3e2fcc145683?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 11,
    type: "indoor",
    typeLabel: "داخلي",
    name: "أجلاونيما",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-aglaonema.jpg",
  },
  {
    id: 12,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بامبو الحظ",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 13,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيلوديندرون برازيـل",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 14,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس نيون",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1596724817753-e5229712bf37?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 15,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس إنجوي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-pothos.jpg",
  },
  {
    id: 16,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس ماربل كوين",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1596724817753-e5229712bf37?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 17,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس مطاط / Rubber Plant",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 18,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا ماسنجانا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-dracaena.jpg",
  },
  {
    id: 19,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا ليمون لايم",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 20,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا كومباكتا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 21,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كالاتيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 22,
    type: "indoor",
    typeLabel: "داخلي",
    name: "مارانتا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 23,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كروتون",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 24,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ببروميا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 25,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ديفنباخيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-aglaonema.jpg",
  },
  {
    id: 26,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ألوكاسيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 27,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كورديلين",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 28,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيتونيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 29,
    type: "indoor",
    typeLabel: "داخلي",
    name: "أوركيد فالاينوبسيس",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 30,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بنفسج إفريقي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1525310072745-f49212b5ac6d?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 31,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بيليا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 32,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كالانشو",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 33,
    type: "indoor",
    typeLabel: "داخلي",
    name: "هويا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 34,
    type: "indoor",
    typeLabel: "داخلي",
    name: "صبار الألوفيرا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1567689265664-1c48de61db0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 35,
    type: "indoor",
    typeLabel: "داخلي",
    name: "صبار داخلي صغير",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 36,
    type: "indoor",
    typeLabel: "داخلي",
    name: "هاروثيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 37,
    type: "indoor",
    typeLabel: "داخلي",
    name: "إيشيفيريا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 38,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سيدوم",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 39,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نبات الصلاة",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 40,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نخلة الأريكا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-areca.jpg",
  },
  {
    id: 41,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نخلة شاميدوريا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1599685315640-9ceab2f58544?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 42,
    type: "indoor",
    typeLabel: "داخلي",
    name: "يوكا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 43,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بيوكارنيا / ذيل الحصان",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 44,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نخلة كينتيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1599685315640-9ceab2f58544?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 45,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس ليراتا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-ficus.jpg",
  },
  {
    id: 46,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس ميكروكاربا / بونساي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1512428559087-560fa5ceab42?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 47,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سينجونيوم",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1600411833196-7c1f6b1a8b90?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 48,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سكندابسوس / بوتس فضي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "/images/plant-pothos.jpg",
  },
  {
    id: 49,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ريكس بيجونيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 50,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نبات القفص الصدري / Monstera Adansonii",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "/images/plant-monstera.jpg",
  },
];

export const outdoorPlants: CatalogPlant[] = [
  {
    id: 1,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "جهنمية",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1528183429752-a97d0bf99b5a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 2,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ياسمين هندي / بلوميريا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1588628566587-dbd176de94b4?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 3,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "واشنطونيا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 4,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "سدر",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 5,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "زيتون",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1541256942802-7b2996a6022e?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 6,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ليمون",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1582281298055-e25b84a30b0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 7,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فيكس بنجامينا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 8,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "نيم",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 9,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "غاف / مسكيت",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1509316975850-ff9c5deb0cd9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 10,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أكاسيا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 11,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تيكوما صفراء",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 12,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "لانتانا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1533038590840-1cde6e668a91?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 13,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كف مريم / فيتكس",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 14,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "دفلة",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 15,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ياسمين بلدي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 16,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ياسمين زفر",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 17,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فل بلدي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 18,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فل جيزاني",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1595152772835-219674b2a8a6?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 19,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "هبسكس",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 20,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كنا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 21,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "بفتة",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 22,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كروتون خارجي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 23,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "روهو",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 24,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أكاليفا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 25,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "جتروفا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 26,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كريسيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 27,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تيكوماريا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 28,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "دادونيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 29,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "بزروميا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 30,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "جاكرندا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1526397751294-331021109fbd?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 31,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "بونسيانا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 32,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "لبخ",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 33,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كورديا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1508615039623-a25605d2b022?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 34,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أكاسيا جلوكا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 35,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "باركنسونيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 36,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فرشاة الزجاج",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1550950158-d0d960dff51b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 37,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تمر هندي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 38,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "رمان",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1541344999736-83eca872f242?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 39,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "توت",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1541344999736-83eca872f242?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 40,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "برتقال",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1582281298055-e25b84a30b0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 41,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "يوسفي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1582281298055-e25b84a30b0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 42,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تين",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1541344999736-83eca872f242?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 43,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "مورينجا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1513836279014-a89f7a76ae86?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 44,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أراك",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1502082553048-f009c37129b9?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 45,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أثل",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 46,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "طلح / سمر",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1516214104703-d870798883c5?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 47,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "صبار أمريكي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 48,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ألوفيرا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1567689265664-1c48de61db0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 49,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "صبار عمودي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 50,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "نخيل عربي / نخيل تمر",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1544077960-604201fe74bc?auto=format&fit=crop&w=600&q=80",
  },
];

export const allPlantsCatalog: CatalogPlant[] = [
  ...indoorPlants,
  ...outdoorPlants.map((p) => ({ ...p, id: p.id + 50 })),
];
