export interface CatalogPlant {
  id: number;
  type: "indoor" | "outdoor";
  typeLabel: "داخلي" | "خارجي";
  name: string;
  scientificOrAlt?: string;
  priority: 1 | 2 | 3;
  priorityBadge: "🔥" | "🔥🔥" | "🔥🔥🔥";
  priorityLabel: "أولوية خاصة" | "أولوية عالية" | "أولوية قصوى";
  image: string;
}

export const indoorPlants: CatalogPlant[] = [
  {
    id: 1,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس ذهبي Pothos",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-pothos.jpg",
  },
  {
    id: 2,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سانسيفيريا / جلد النمر",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-sansevieria.jpg",
  },
  {
    id: 3,
    type: "indoor",
    typeLabel: "داخلي",
    name: "الزاميا ZZ",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Zamioculcas_zamiifolia_1.jpg/330px-Zamioculcas_zamiifolia_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 4,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيلوديندرون القلب",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bb/Philodendron_scandens_subsp_oxycardium2.jpg/330px-Philodendron_scandens_subsp_oxycardium2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 5,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سبايدر بلانت / نبات العنكبوت",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/05/Chlorophytum_comosum%2C_flores.jpg/960px-Chlorophytum_comosum%2C_flores.jpg",
  },
  {
    id: 6,
    type: "indoor",
    typeLabel: "داخلي",
    name: "مونستيرا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-monstera.jpg",
  },
  {
    id: 7,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-dracaena.jpg",
  },
  {
    id: 8,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس بنجامينا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "/images/plant-ficus.jpg",
  },
  {
    id: 9,
    type: "indoor",
    typeLabel: "داخلي",
    name: "شفليرا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/82/Schefflera_arboricola%2C_vrugte%2C_a%2C_Pretoria.jpg/330px-Schefflera_arboricola%2C_vrugte%2C_a%2C_Pretoria.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 10,
    type: "indoor",
    typeLabel: "داخلي",
    name: "أنثوريوم",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8b/AnthuriumAndraenum.jpg/330px-AnthuriumAndraenum.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 11,
    type: "indoor",
    typeLabel: "داخلي",
    name: "أجلاونيما",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-aglaonema.jpg",
  },
  {
    id: 12,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بامبو الحظ",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e2/Dracaena_sanderiana_2.jpg/330px-Dracaena_sanderiana_2.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 13,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيلوديندرون برازيـل",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1614594975525-e45190c55d0b?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 14,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس نيون",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1596724817753-e5229712bf37?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 15,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس إنجوي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1616046229478-9901c5536a45?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 16,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بوتس ماربل كوين",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1598880940371-c756e015fea1?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 17,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس مطاط / Rubber Plant",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/16/Ficus_elastica_leaves_02.JPG/330px-Ficus_elastica_leaves_02.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 18,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا ماسنجانا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Dracaena_fragrans_%282%29.jpg/330px-Dracaena_fragrans_%282%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 19,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا ليمون لايم",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/61/Dracaena_reflexa.JPG/330px-Dracaena_reflexa.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 20,
    type: "indoor",
    typeLabel: "داخلي",
    name: "دراسينا كومباكتا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1598880940080-ff9a29891b85?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 21,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كالاتيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/CalatheaMakoyana.jpg/330px-CalatheaMakoyana.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 22,
    type: "indoor",
    typeLabel: "داخلي",
    name: "مارانتا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Maranta_leuconeura3.jpg/330px-Maranta_leuconeura3.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 23,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كروتون",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bf/Colpfl05.jpg/330px-Colpfl05.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 24,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ببروميا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ac/Peperomia_argyreia.jpg/330px-Peperomia_argyreia.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 25,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ديفنباخيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e0/Starr_061212-2331_Dieffenbachia_seguine.jpg/330px-Starr_061212-2331_Dieffenbachia_seguine.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 26,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ألوكاسيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Alocasia_x_amazonica_a1.jpg/330px-Alocasia_x_amazonica_a1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 27,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كورديلين",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Cordyline_fruticosa_%2820262433874%29.jpg/330px-Cordyline_fruticosa_%2820262433874%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 28,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيتونيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/50/Acanthaceae_leaf.jpg/330px-Acanthaceae_leaf.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 29,
    type: "indoor",
    typeLabel: "داخلي",
    name: "أوركيد فالاينوبسيس",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1e/Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg/330px-Phalaenopsis_philippinensis_NationalOrchidGarden-Singapore.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 30,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بنفسج إفريقي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a0/Saintpaulia_ionantha.jpg/330px-Saintpaulia_ionantha.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 31,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بيليا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6d/Pilea_peperomioides_Chinese_money_plant.jpg/330px-Pilea_peperomioides_Chinese_money_plant.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 32,
    type: "indoor",
    typeLabel: "داخلي",
    name: "كالانشو",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/8d/Kalanchoe_blossfeldiana_3.jpg/330px-Kalanchoe_blossfeldiana_3.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 33,
    type: "indoor",
    typeLabel: "داخلي",
    name: "هويا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ea/NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg/330px-NKN-2007-06-13_114250_Hoya_Carnosa_%28Yvan_Leduc_author_for_Wikipedia%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 34,
    type: "indoor",
    typeLabel: "داخلي",
    name: "صبار الألوفيرا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4b/Aloe_vera_flower_inset.png/330px-Aloe_vera_flower_inset.png?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 35,
    type: "indoor",
    typeLabel: "داخلي",
    name: "صبار داخلي صغير",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1459411552884-841db9b3cc2a?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 36,
    type: "indoor",
    typeLabel: "داخلي",
    name: "هاروثيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b9/Haworthia_cymbiformis_1.jpg/330px-Haworthia_cymbiformis_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 37,
    type: "indoor",
    typeLabel: "داخلي",
    name: "إيشيفيريا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/85/Echeveria_elegans_-_1.jpg/330px-Echeveria_elegans_-_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 38,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سيدوم",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Sedum_acre_single_-_Niitv%C3%A4lja.jpg/330px-Sedum_acre_single_-_Niitv%C3%A4lja.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 39,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نبات الصلاة",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Goeppertia_roseopicta.jpg/330px-Goeppertia_roseopicta.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 40,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نخلة الأريكا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "/images/plant-areca.jpg",
  },
  {
    id: 41,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نخلة شاميدوريا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/64/Chamaedorea_elegans_Mart.JPG/330px-Chamaedorea_elegans_Mart.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 42,
    type: "indoor",
    typeLabel: "داخلي",
    name: "يوكا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/bd/Yucca_gigantea_-_Jard%C3%ADn_Bot%C3%A1nico_Canario_Viera_y_Clavijo_-_Gran_Canaria.jpg/330px-Yucca_gigantea_-_Jard%C3%ADn_Bot%C3%A1nico_Canario_Viera_y_Clavijo_-_Gran_Canaria.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 43,
    type: "indoor",
    typeLabel: "داخلي",
    name: "بيوكارنيا / ذيل الحصان",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7e/Beaucarnea_recurvata%2C_Ocampo%2C_Tamaulipas%2C_Mexico_1.jpg/330px-Beaucarnea_recurvata%2C_Ocampo%2C_Tamaulipas%2C_Mexico_1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 44,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نخلة كينتيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/9/99/Howea_forsteriana_Lord_Howe_Island.jpg/330px-Howea_forsteriana_Lord_Howe_Island.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 45,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس ليراتا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Starr_031108-0130_Ficus_lyrata.jpg/330px-Starr_031108-0130_Ficus_lyrata.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 46,
    type: "indoor",
    typeLabel: "داخلي",
    name: "فيكس ميكروكاربا / بونساي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/24/Ficus_microcarpa_-_La_Gomera_01.jpg/330px-Ficus_microcarpa_-_La_Gomera_01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 47,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سينجونيوم",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/58/Zingiber_malaysianum.jpg/330px-Zingiber_malaysianum.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 48,
    type: "indoor",
    typeLabel: "داخلي",
    name: "سكندابسوس / بوتس فضي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Scindapsus_pictus_01.jpg/330px-Scindapsus_pictus_01.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 49,
    type: "indoor",
    typeLabel: "داخلي",
    name: "ريكس بيجونيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Begonia_obliqua00.jpg/330px-Begonia_obliqua00.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 50,
    type: "indoor",
    typeLabel: "داخلي",
    name: "نبات القفص الصدري / Monstera Adansonii",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fb/Monstera_adansonii_79319231.jpg/330px-Monstera_adansonii_79319231.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
];

export const outdoorPlants: CatalogPlant[] = [
  {
    id: 1,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "جهنمية",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Starr_030418-0061_Bougainvillea_spectabilis.jpg/330px-Starr_030418-0061_Bougainvillea_spectabilis.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 2,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ياسمين هندي / بلوميريا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/ef/Plumeria_alba2709449426.jpg/330px-Plumeria_alba2709449426.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 3,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "واشنطونيا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b8/Washingtonia_filifera.jpg/330px-Washingtonia_filifera.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 4,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "سدر",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/84/Ziziphus-areva-israel.jpg/330px-Ziziphus-areva-israel.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 5,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "زيتون",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2d/Olea_europaea_cuspidata-africana_Cape_Town.JPG/330px-Olea_europaea_cuspidata-africana_Cape_Town.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 6,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ليمون",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/P1030323.JPG/330px-P1030323.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 7,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فيكس بنجامينا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 8,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "نيم",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/7b/Neem_Tree_in_Rajasthan%2C_India.jpg/330px-Neem_Tree_in_Rajasthan%2C_India.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 9,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "غاف / مسكيت",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/7/78/Prosopis_cineraria_-_Khejri.jpg/330px-Prosopis_cineraria_-_Khejri.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 10,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أكاسيا",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Macro_view_of_thorn_and_leaves_of_a_Babul_tree_%28Vachellia_nilotica%29_from_Rajasthan%2C_India.jpg/330px-Macro_view_of_thorn_and_leaves_of_a_Babul_tree_%28Vachellia_nilotica%29_from_Rajasthan%2C_India.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 11,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تيكوما صفراء",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/db/Ip%C3%AA-de-jardim_%28do_tupi_%27yp%C3%A9%29%2C_Tecoma_stans%2C_em_Bag%C3%A9-RS%2C_Brasil.jpg/330px-Ip%C3%AA-de-jardim_%28do_tupi_%27yp%C3%A9%29%2C_Tecoma_stans%2C_em_Bag%C3%A9-RS%2C_Brasil.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 12,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "لانتانا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/LantanaFlowerLeaves.jpg/330px-LantanaFlowerLeaves.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 13,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كف مريم / فيتكس",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a1/Vitex_agnus-castus_1.JPG/330px-Vitex_agnus-castus_1.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 14,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "دفلة",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Nerium_oleander_flowers_leaves.jpg/330px-Nerium_oleander_flowers_leaves.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 15,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ياسمين بلدي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/27/Jasminum_grandiflorum_%28Oleaceae%29.jpg/330px-Jasminum_grandiflorum_%28Oleaceae%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 16,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ياسمين زفر",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/22/Volkameria_inermis_308123521.jpg/330px-Volkameria_inermis_308123521.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 17,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فل بلدي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f3/Arabian_jasmin%2C_Tunisia_2010.jpg/330px-Arabian_jasmin%2C_Tunisia_2010.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 18,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فل جيزاني",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1597055181300-e3633a917c9c?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 19,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "هبسكس",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/21/Hibiscus_Brilliant.jpg/330px-Hibiscus_Brilliant.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 20,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كنا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/1c/Cinnamon-bellied_flowerpiercer_%28Diglossa_baritula%29_male_on_Indian_shot_%28Canna_indica%29_Finca_El_Pilar.jpg/330px-Cinnamon-bellied_flowerpiercer_%28Diglossa_baritula%29_male_on_Indian_shot_%28Canna_indica%29_Finca_El_Pilar.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 21,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "بفتة",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Vinca_%28Catharanthus_roseus%29_cultivada_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55231652268.jpg/330px-Vinca_%28Catharanthus_roseus%29_cultivada_em_Bag%C3%A9%2C_RS%2C_Brasil_-_55231652268.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 22,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كروتون خارجي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://images.unsplash.com/photo-1512428813834-c702c7702b78?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 23,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "روهو",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e1/Tradescantia_spathacea_%28_Moses-in-the-cradle_%29.jpg/330px-Tradescantia_spathacea_%28_Moses-in-the-cradle_%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 24,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أكاليفا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Acalypha_Flamengueira2.JPG/330px-Acalypha_Flamengueira2.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 25,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "جتروفا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/13/Jatropha_interregima.JPG/330px-Jatropha_interregima.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 26,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كريسيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/17/Starr_010820-0009_Carissa_macrocarpa.jpg/330px-Starr_010820-0009_Carissa_macrocarpa.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 27,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تيكوماريا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/Tecoma_capensis_2922.jpg/330px-Tecoma_capensis_2922.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 28,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "دادونيا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/d1/Dodonaea_viscosa_%28Hopbush%29_W2_IMG_1899.jpg/330px-Dodonaea_viscosa_%28Hopbush%29_W2_IMG_1899.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 29,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "بزروميا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3d/Conocarpus_erectus_Key_Largo.jpg/330px-Conocarpus_erectus_Key_Largo.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 30,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "جاكرندا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cb/Jacarand%C3%A1-mimoso_%28do_tupi_%C3%AEakarand%C3%A1%29_-_54942878507_02.jpg/330px-Jacarand%C3%A1-mimoso_%28do_tupi_%C3%AEakarand%C3%A1%29_-_54942878507_02.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 31,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "بونسيانا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/87/Royal_Poinciana.jpg/330px-Royal_Poinciana.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 32,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "لبخ",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/0/0c/Starr_080531-4752_Albizia_lebbeck.jpg/330px-Starr_080531-4752_Albizia_lebbeck.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 33,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "كورديا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a6/Scarlet_cordia.jpg/330px-Scarlet_cordia.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 34,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أكاسيا جلوكا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/a/a7/Starr_080314-3425_Senna_surattensis.jpg/330px-Starr_080314-3425_Senna_surattensis.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 35,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "باركنسونيا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/69/ParkinsoniaAculeata.jpg/330px-ParkinsoniaAculeata.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 36,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "فرشاة الزجاج",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/8/86/Melaleuca_viminalis.jpg/330px-Melaleuca_viminalis.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 37,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تمر هندي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Tamarindus_indica_pods.JPG/330px-Tamarindus_indica_pods.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 38,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "رمان",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/6/6a/Pomegranate_Juice_%282019%29.jpg/330px-Pomegranate_Juice_%282019%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 39,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "توت",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/47/Rosales_-_Morus_alba_-_3.jpg/330px-Rosales_-_Morus_alba_-_3.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 40,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "برتقال",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b0/OrangeBloss_wb.jpg/330px-OrangeBloss_wb.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 41,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "يوسفي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/1/10/Citrus_reticulata_April_2013_Nordbaden.JPG/330px-Citrus_reticulata_April_2013_Nordbaden.JPG?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 42,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "تين",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/Ficus_carica_L%2C_1771.jpg/330px-Ficus_carica_L%2C_1771.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 43,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "مورينجا",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2e/DrumstickFlower.jpg/330px-DrumstickFlower.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 44,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أراك",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/e/e4/Peelo_10.jpg/330px-Peelo_10.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 45,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "أثل",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/d/da/Tamaris3.jpg/330px-Tamaris3.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 46,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "طلح / سمر",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/c/ca/Vachellia_%28ex_Acacia%29_tortilis.jpg/330px-Vachellia_%28ex_Acacia%29_tortilis.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 47,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "صبار أمريكي",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Agave_July_2011-1.jpg/330px-Agave_July_2011-1.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 48,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "ألوفيرا",
    priority: 2,
    priorityBadge: "🔥🔥",
    priorityLabel: "أولوية عالية",
    image: "https://images.unsplash.com/photo-1509423350716-97f9360b4e09?auto=format&fit=crop&w=600&q=80",
  },
  {
    id: 49,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "صبار عمودي",
    priority: 1,
    priorityBadge: "🔥",
    priorityLabel: "أولوية خاصة",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/5/53/Cereus_repandus_in_Aruba_-_on_the_way_back_from_Altovista_chapel_%282896840490%29.jpg/330px-Cereus_repandus_in_Aruba_-_on_the_way_back_from_Altovista_chapel_%282896840490%29.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
  {
    id: 50,
    type: "outdoor",
    typeLabel: "خارجي",
    name: "نخيل عربي / نخيل تمر",
    priority: 3,
    priorityBadge: "🔥🔥🔥",
    priorityLabel: "أولوية قصوى",
    image: "https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Dates005.jpg/330px-Dates005.jpg?utm_source=en.wikipedia.org&utm_campaign=api&utm_content=thumbnail",
  },
];

export const allPlantsCatalog: CatalogPlant[] = [
  ...indoorPlants,
  ...outdoorPlants.map((p) => ({ ...p, id: p.id + 50 })),
];
